
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from '../components/Table'
import Form from '../components/Form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className="text-center text-3xl text-gray-600 font-bold underline m-7 p-5">
        Create Your Custom Forms!!
      </h1>


    <Table />
    
    <Form/>

      

      
    </div>
  )
}
